/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 716ddd93e33e723f75b642df13247bd3)
interface __BaseEnv_Env {
	PLAN_STORE: KVNamespace;
	EKUBO_API_URL: string;
	EKUBO_QUOTER_URL: string;
	ZERO_X_API_KEY: string;
	ACROSS_API_KEY: string;
	ACROSS_INTEGRATOR_ID: string;
	DUNE_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EKUBO_API_URL" | "EKUBO_QUOTER_URL" | "ZERO_X_API_KEY" | "ACROSS_API_KEY" | "ACROSS_INTEGRATOR_ID" | "DUNE_API_KEY">> {}
}
