/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 2b9c4e66f578c44e5eee31e176b1a5e1)
interface __BaseEnv_Env {
	ARTIFACT_STORE: R2Bucket;
	RATE_LIMITER_BURST: RateLimit;
	RATE_LIMITER: RateLimit;
	RATE_LIMITER_TOOLS: RateLimit;
	RATE_LIMITER_METERED: RateLimit;
	EKUBO_API_URL: string;
	EKUBO_QUOTER_URL: string;
	ZERO_X_API_KEY: string;
	ACROSS_API_KEY: string;
	ACROSS_INTEGRATOR_ID: string;
	DUNE_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EKUBO_API_URL" | "EKUBO_QUOTER_URL" | "ZERO_X_API_KEY" | "ACROSS_API_KEY" | "ACROSS_INTEGRATOR_ID" | "DUNE_API_KEY">> {}
}
