import { type Address, decodeFunctionData, erc20Abi, type Hex } from "viem";

/**
 * Tokens whose `approve` refuses to replace a nonzero allowance with another
 * nonzero amount, so the allowance has to be set to zero first.
 *
 * Every plan this server builds ends by returning the allowance to zero, so
 * within its own flows the second approval never collides. The collision is
 * cross-tool: the interface grants an *unlimited* allowance by default, so a
 * user who approved there and then came here arrives with a standing nonzero
 * allowance that this server, being stateless about chain state, cannot see.
 *
 * Keyed by chain and address, never by symbol. The guard belongs to a
 * particular deployment: mainnet USDT has it and no bridged USDT does, so a
 * symbol match would make every L2 pay for a reset it does not need.
 *
 * Generated by probing every token in the Ekubo list on each chain, four
 * approvals deep -- approve(n), approve(2n), approve(0), approve(3n) -- and
 * keeping the tokens where the second fails and the fourth succeeds. A token
 * returning false counts as failing, since a silent false leaves the
 * allowance unchanged and breaks the spend later instead. Two independent
 * probes agreed on every entry: `eth_simulateV1`, and a prober contract
 * injected with an `eth_call` state override for the chains whose RPCs do not
 * implement it. 11,481 tokens scanned on 2026-08-20; the 91 below have it.
 *
 * FUN (0x419d0d8b) and META (0xde2f7766) on mainnet carry the guard but are
 * deliberately absent: approve(0) reverts for them too, so the reset this
 * list triggers could not recover them and would only add a failing step to
 * plans that work today.
 *
 * Robinhood Chain was scanned and has none, hence no entry. The Ekubo
 * interface mirrors this list in `src/util/evm/allowanceReset.ts`.
 */
const TOKENS_REQUIRING_ALLOWANCE_RESET: ReadonlyMap<
  bigint,
  ReadonlySet<bigint>
> = new Map([
  [
    1n,
    new Set([
      0x6c3f90f043a72fa612cbac8115ee7e52bde6e490n, // 3Crv
      0xcd62b1c403fa761baadfc74c525ce2b51780b184n, // ANJ
      0x960b236a07cf122663c4303350609a66a7b288c0n, // ANTv1
      0x3472a5a71965499acd81997a54bba8d852c6e53dn, // BADGER
      0xf920e4f3fbef5b3ad0a25017514b769bdc4ac135n, // BAX
      0xd945d2031b4c63c0e363304fb771f709b502dc0an, // BMC
      0xbbbb2d4d765c1e455e4896a64ba3883e914abbbbn, // BMP
      0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1cn, // BNT
      0xef19f4e48830093ce5bc8b3ff7f903a0ae3e9fa1n, // BOTX
      0xa0a675d08ca63066f48408136f8a71fc65be4afcn, // BZR
      0x954b890704693af242613edef1b603825afcd708n, // CARD
      0x72953a5c32413614d24c29c84a66ae4b59581bbfn, // CLEV
      0xd4c435f5b09f855c3317c8524cb1f586e42795fan, // CND
      0x42baf1f659d765c65ade5bb7e08eb2c680360d9dn, // COPI
      0xd533a949740bb3306d119cc777fa900ba034cd52n, // CRV
      0x075b1bb99792c9e1041ba13afef80c91a1e70fb3n, // CRVRENWSBTC
      0xb3ad645db386d7f6d753b2b9c3f4b853da6890b8n, // CTR
      0x41e5560054824ea6b0732e656e3ad64e20e94e45n, // CVC
      0xb6ee9668771a79be7967ee29a63d4184f8097143n, // CXO
      0x3597bfd533a99c9aa083587b074434e61eb0a258n, // DENT
      0x431ad2ff6a9c365805ebad47ee021148d6f7dbe0n, // DF
      0x5dc60c4d5e75d22588fa17ffeb90a63e535efce0n, // DKA
      0x0abdace70d3790235af448c88547603b945604ean, // DNT
      0x4957805230831401caad5b690aa138143b711358n, // DORA
      0xac3211a5025414af2866ff09c23fc18bc97e79b1n, // DOV
      0x3ab6ed69ef663bd986ee59205ccad8a20f98b4c2n, // DREP
      0x9d5963ba32e877871dff3e2e697283dc64066271n, // EDC
      0x8a7b7b9b2f7d0c63f66171721339705a6188a7d5n, // EDOGE
      0xc2708a3a4ba7f64bddc1a49f92f941bc77cad23an, // EGG
      0xf629cbd94d3791c9250152bd8dfbdf380e2a3b9cn, // ENJ
      0x365accfca291e7d3914637abf1f7635db165bb09n, // FXN
      0x8a854288a5976036a725879164ca3e91d30c6a1bn, // GET
      0x3f382dbd960e3a9bbceae22651e88158d2791550n, // GHST
      0xc4f6e93aeddc11dc22268488465babcaf09399acn, // HI
      0x95e40e065afb3059dcabe4aaf404c1f92756603an, // KDAG
      0xdd974d5c2e2928dea5f71b9825b8b646686bd200n, // KNC
      0x2c2d8a078b33bf7782a16acce2c5ba6653a90d5fn, // L3USD
      0x5a98fcbea516cf06857215779fd812ca3bef1b32n, // LDO
      0x80fb784b7ed66730e8b1dbd9820afd29931aab03n, // LEND
      0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3n, // LEO
      0xa444ec96ee01bb219a44b285de47bf33c3447ad5n, // LEOX
      0x3b9be07d622accaed78f479bc0edabfd6397e320n, // LSS
      0x0f5d2fb29fb7d3cfee444a200298f468908cc942n, // MANA
      0x06f3c323f0238c72bf35011071f2b5b7f43a054cn, // MASQ
      0x814e0908b12a99fecf5bc101bb5d0b8b5cdf7d26n, // MDT
      0xd3e4ba569045546d09cf021ecc5dfe42b1d7f6e4n, // MNW
      0xf433089366899d83a9f26a773d59ec7ecf30355en, // MTL
      0x6226e00bcac68b0fe55583b90a1d727c14fab77fn, // MTV
      0xa849eaae994fb86afa73382e9bd88c2b6b18dc71n, // MVL
      0x87d73e916d7057945c9bcd8cdd94e42a6f47f776n, // NFTX
      0x5cf04716ba20127f1e2297addcf4b5035000c9ebn, // NKN
      0x1776e1f26f98b1a5df9cd347953a26dd3cb46671n, // NMR
      0x4fe83213d56308330ec302a8bd641f1d0113a4ccn, // NU
      0xd26114cd6ee289accf82350c8d8487fedb8a0c07n, // OMG
      0x4527a3b4a8a150403090a99b87effc96f2195047n, // P2PS
      0xe3818504c1b32bf1557b16c238b2e01fd3149c17n, // PLR
      0xd4fa1460f537bb9085d22c7bccb5dd450ef28e3an, // PPT
      0x8ae4bf2c33a8e667de34b54938b0ccd03eb8cc06n, // PTOY
      0x49849c98ae39fff122806c06791fa73784fb3675n, // RENBTCCURVE
      0xd101dcc414f310268c37eeb4cd376ccfa507f571n, // RSC
      0xc25a3a3b969415c80451098fa907ec722572917fn, // SCURVE
      0x0f5def84ced3e9e295dae28df96d0b846de92c1an, // SDG
      0x40fed5691e547885cabd7a2990de719dcc8497fcn, // SHA
      0xfdd070e34cbd0923d307f3af481be5bddac4f487n, // SMPL
      0x744d70fdbe2ba4cf95131626614a1763df805b9en, // SNT
      0xb4a3b0faf0ab53df58001804dda5bfc6a3d59008n, // SPA
      0xb64ef51c888972c908cfacf59b47c1afbc0ab8acn, // STORJ
      0x006bea43baa3f7a6f765f14f10a1a1b08334ef45n, // STX
      0x77c6e4a580c0dce4e5c7a17d0bc077188a83a059n, // SWUSD
      0x68a47fe1cf42eba4a030a10cd4d6a1031ca3ca0an, // TET
      0xaaaf91d9b90df800df4f55c205fd6989c977e73an, // TKN
      0xaa7a9ca87d3694b5755f213b5d04094b8d0f0a6fn, // TRAC
      0xf5b5efc906513b4344ebabcf47a04901f99f09f3n, // UBX
      0x226f7b842e0f0120b7e194d05432b3fd14773a9dn, // UNN
      0x8806926ab68eb5a7b909dcaf6fdbe5d93271d6e2n, // UQC
      0xdac17f958d2ee523a2206206994597c13d831ec7n, // USDT
      0x340d2bde5eb28c1eed91b2f790723e3b160613b7n, // VEE
      0xed40834a13129509a89be39a9be9c0e96a0ddd71n, // WARP
      0x0cf0ee63788a0849fe5297f3407f701e122cc023n, // XDATA
      0xa974c709cfb4566686553a20790685a47aceaa33n, // XIN
    ]),
  ],
  [
    10n,
    new Set([
      0xa0a675d08ca63066f48408136f8a71fc65be4afcn, // BZR
      0x650af3c15af43dcb218406d30784416d64cfb6b2n, // SNT
    ]),
  ],
  [
    137n,
    new Set([
      0x33b6d77c607ea499ab5db7e2201c5a516a78a5dbn, // AIMX
      0xa0a675d08ca63066f48408136f8a71fc65be4afcn, // BZR
      0x51de72b17c7bd12e9e6d69eb506a669eb6b5249en, // EGG
      0x2c2d8a078b33bf7782a16acce2c5ba6653a90d5fn, // L3USD
      0x534f39c5f4df9cb13e16b24ca07c7c8c0e2eadb7n, // SHA
    ]),
  ],
  [
    8453n,
    new Set([
      0xa0a675d08ca63066f48408136f8a71fc65be4afcn, // BZR
      0xc0634090f2fe6c6d75e61be2b949464abb498973n, // KTA
    ]),
  ],
  [
    42161n,
    new Set([
      0xa0a675d08ca63066f48408136f8a71fc65be4afcn, // BZR
    ]),
  ],
  [
    43114n,
    new Set([
      0xa0a675d08ca63066f48408136f8a71fc65be4afcn, // BZR
    ]),
  ],
]);

export function requiresAllowanceReset(
  chainId: string | bigint,
  token: string | bigint,
): boolean {
  return (
    TOKENS_REQUIRING_ALLOWANCE_RESET.get(BigInt(chainId))?.has(
      BigInt(token),
    ) === true
  );
}

/**
 * The spender of an `approve` call that sets a nonzero allowance, or null for
 * anything else.
 *
 * A zero approval is excluded deliberately: revocations and the trailing
 * cleanup step are the very calls that clear the collision, and prefixing them
 * with another zero approval would add a step that does nothing. Calldata that
 * is not an `approve` at all decodes to null rather than throwing, because
 * step kinds are producer-assigned labels and a mislabeled step must not take
 * down the whole plan.
 */
export function nonzeroApprovalSpender(data: Hex): Address | null {
  let decoded;
  try {
    decoded = decodeFunctionData({ abi: erc20Abi, data });
  } catch {
    return null;
  }
  if (decoded.functionName !== "approve") return null;
  const [spender, amount] = decoded.args;
  return amount === 0n ? null : spender;
}
