import { ServiceError } from "./core.js";
import policy from "./jurisdiction-policy.json";

/**
 * Jurisdiction restrictions on tradable assets, policy
 * `ekubo-token-jurisdictions-v2` (CLO decision EKU-853, 2026-10-06).
 *
 * The policy data lives in `jurisdiction-policy.json`, generated by
 * `script/generate-jurisdiction-policy.mjs` and shared byte-for-byte with the
 * Ekubo interface (`src/util/common/jurisdictionPolicy.json`); both repositories
 * pin its SHA-256 in a test so the two cannot drift silently. The interface
 * disables its action buttons; this server refuses to produce an execution plan
 * at all, which is the equivalent control for a caller that has no UI to
 * disable. Swap quotes and their plans return restriction metadata for the
 * agent/wallet to evaluate before execution. Other preparation tools retain
 * this gate. Discovery is deliberately untouched: `list_tokens`, `get_token`,
 * and the opportunity tools still list and price every asset.
 *
 * The rule is a class rule, not an address list that happens to be complete:
 *
 * - On a chain the policy covers, every token is classified. A Robinhood Stock
 *   Token (`rhj_stock_token`) is restricted for the class's jurisdictions on
 *   both sides; there is no disposal exemption. An exact address verified
 *   outside the class (`outside_class`) is not restricted by this rule.
 * - Any other token on that chain is `unclassified` and held: no plan is
 *   prepared for it anywhere, and quote metadata says `execution_hold`. A new
 *   issuer listing therefore fails closed until it is classified.
 * - A chain the policy does not cover is `out_of_scope`.
 *
 * Country codes are ISO 3166-1 alpha-2: https://www.iso.org/obp/ui/#search
 */

export const JURISDICTION_POLICY_VERSION = policy.policy_version;

export type AssetClassification =
  | "rhj_stock_token"
  | "outside_class"
  | "unclassified"
  | "out_of_scope";

interface ChainPolicy {
  readonly rhjStockTokens: ReadonlyMap<bigint, readonly string[]>;
  readonly outsideClass: ReadonlyMap<bigint, string>;
}

const RHJ_STOCK_TOKEN_COUNTRIES: readonly string[] = [
  ...policy.classes.rhj_stock_token.restricted_jurisdictions.product_policy,
  ...policy.classes.rhj_stock_token.restricted_jurisdictions
    .issuer_prohibited_investor,
].sort();
const RHJ_STOCK_TOKEN_COUNTRY_SET: ReadonlySet<string> = new Set(
  RHJ_STOCK_TOKEN_COUNTRIES,
);

const CHAIN_POLICIES: ReadonlyMap<bigint, ChainPolicy> = new Map(
  Object.entries(policy.chains).map(([chainId, chain]) => {
    if (chain.unclassified !== "hold") {
      throw new Error(`jurisdiction policy: chain ${chainId} must hold unclassified assets`);
    }
    return [
      BigInt(chainId),
      {
        rhjStockTokens: new Map(
          chain.rhj_stock_token.map((entry) => [BigInt(entry.address), entry.sources]),
        ),
        outsideClass: new Map(
          chain.outside_class.map((entry) => [BigInt(entry.address), entry.basis]),
        ),
      },
    ];
  }),
);

export interface AssetClass {
  classification: AssetClassification;
  /**
   * Where the classification comes from: the class sources for a class member
   * (`issuer_registry`, `curated`, `ekubo_v1`), the verification basis for an
   * asset outside the class, and nothing otherwise.
   */
  sources: readonly string[];
}

export function classifyAsset(
  chainId: string | bigint,
  token: string | bigint,
): AssetClass {
  const chain = CHAIN_POLICIES.get(BigInt(chainId));
  if (chain === undefined) return { classification: "out_of_scope", sources: [] };
  const address = BigInt(token);
  const sources = chain.rhjStockTokens.get(address);
  if (sources !== undefined) return { classification: "rhj_stock_token", sources };
  const basis = chain.outsideClass.get(address);
  if (basis !== undefined) return { classification: "outside_class", sources: [basis] };
  return { classification: "unclassified", sources: [] };
}

function restrictedJurisdictionsFor(
  classification: AssetClassification,
): readonly string[] {
  return classification === "rhj_stock_token" ? RHJ_STOCK_TOKEN_COUNTRIES : [];
}

/**
 * The requesting country, or null when the edge did not resolve one.
 *
 * Null is not "allowed": for an asset that is actually restricted somewhere it
 * fails closed, because an unresolved origin cannot be shown to be outside the
 * restricted set. It is scoped to those assets only — an unresolved country
 * must never restrict trading generally.
 */
export type RequestCountry = string | null;

/**
 * Read the country Cloudflare inferred from the connecting IP.
 *
 * `request.cf` is set by the edge and cannot be supplied by the client, which
 * is why the client-controlled `x-forwarded-for`-style headers are not
 * consulted here — the same reasoning `rateLimitActor` applies to
 * `cf-connecting-ip`. This must be called with the *original* Request:
 * `admitMcpRequest` replays a POST through `new Request(url, init)`, which
 * carries the headers over but drops `cf`.
 *
 * `T1` is Cloudflare's code for a request arriving from the Tor network, which
 * names no jurisdiction. It is reported as unresolved so a restricted asset
 * fails closed rather than passing an ISO country-code comparison it can never
 * match. The interface applies the same rule in `resolvedCountryCode`.
 *
 * The connection country is a signal about the connection, not the user's
 * legal domicile, residence, US-person status, or eligibility.
 */
export function requestCountry(request: Request): RequestCountry {
  const country = (request as Request & { cf?: { country?: string } }).cf
    ?.country;
  if (typeof country !== "string" || country.length === 0) return null;
  return country.toUpperCase() === "T1" ? null : country;
}

/**
 * Whether this server refuses to prepare a plan that moves the token for a
 * caller connecting from `country`.
 *
 * Unclassified assets on a covered chain are held for every country, because
 * an empty restriction list for them would be a false negative.
 */
export function isTokenCountryRestricted({
  chainId,
  token,
  country,
}: {
  chainId: string | bigint;
  token: string | bigint;
  country: RequestCountry;
}): boolean {
  const { classification } = classifyAsset(chainId, token);
  if (classification === "unclassified") return true;
  if (classification !== "rhj_stock_token") return false;
  if (country === null) return true;
  return RHJ_STOCK_TOKEN_COUNTRY_SET.has(country.toUpperCase());
}

/** One asset a caller asked this server to build a transaction around. */
export interface RestrictableAsset {
  chainId: string | bigint;
  token: string | bigint | undefined;
  side: AssetSide;
}

/**
 * Which way an asset moves in the transaction being prepared.
 *
 * `sell` means the caller gives the asset up: the swap input, the TWAMM or
 * auction sell token, a claimed fee balance being swapped away. `buy` means the
 * caller ends up holding it. Anything that is neither — a pool pair being
 * rebalanced, a token whose oracle capacity is being extended — is `buy`.
 *
 * Policy v2 restricts both sides identically (EKU-853 removed the v1 disposal
 * exemption), so the side is reported in metadata but does not change the
 * decision.
 */
export type AssetSide = "sell" | "buy";

function hexAddress(token: string | bigint): string {
  return `0x${BigInt(token).toString(16).padStart(40, "0")}`;
}

function restrictionMessage(
  blocked: readonly { classification: AssetClassification }[],
  country: RequestCountry,
): string {
  const suffix =
    " No execution plan was prepared. Do not retry through another network path or another Ekubo tool: the same policy applies to every path that would trade it, in either direction.";
  if (blocked.some((asset) => asset.classification === "unclassified")) {
    return `This asset has no classification under ${JURISDICTION_POLICY_VERSION}, so execution is held until it is classified.${suffix}`;
  }
  if (country === null) {
    return `This asset is unavailable because the country of the requesting IP address could not be determined.${suffix}`;
  }
  return `This asset is unavailable in your region (${country.toUpperCase()}).${suffix}`;
}

/**
 * Refuse to prepare anything that trades an asset the caller's jurisdiction
 * restricts or the policy has not classified. Call this before spending
 * upstream quote credit, not after: a plan that is never built is also never
 * charged for.
 *
 * Assets with no token — an optional argument the caller omitted — are skipped
 * rather than treated as the native token, which would silently check the
 * wrong thing.
 */
export function assertAssetsTradable(
  assets: readonly RestrictableAsset[],
  country: RequestCountry,
): void {
  const blocked = assets.flatMap((asset) => {
    if (asset.token === undefined) return [];
    if (!isTokenCountryRestricted({ chainId: asset.chainId, token: asset.token, country })) {
      return [];
    }
    const { classification } = classifyAsset(asset.chainId, asset.token);
    return [{
      chain_id: BigInt(asset.chainId).toString(),
      token: hexAddress(asset.token),
      side: asset.side,
      classification,
    }];
  });
  if (blocked.length === 0) return;

  throw new ServiceError(
    "restricted_jurisdiction",
    restrictionMessage(blocked, country),
    {
      policy_version: JURISDICTION_POLICY_VERSION,
      country,
      restricted_assets: blocked,
    },
  );
}

/**
 * Public policy notice (EKU-853 §3), independent of the caller's location or
 * domicile.
 */
export const QUOTE_JURISDICTION_NOTICE = "A quote, execution plan, simulation or wallet approval is not permission to trade. Robinhood Stock Tokens are tokenised debt securities subject to issuer restrictions and applicable law. Before requesting signatures or submitting approvals or trades, establish the user's relevant jurisdiction and eligibility, including location, residence or entity incorporation, US-person status under Regulation S, any person for whose account or benefit the transaction is made, and issuer Prohibited Investor restrictions. Never infer these facts from an agent or server IP. If required facts or asset-policy coverage are unknown, do not proceed. Only the user or an authorized representative of the actual investor may provide an explicit factual attestation; an agent must not attest on their behalf. A known prohibited fact cannot be overridden by attestation. An attestation is not a license, legal exemption or substitute for required screening. Keep the attestation client-side; do not send it to the quote API or MCP server. No blanket disposal exemption applies.";

/**
 * Jurisdiction metadata for a quote or plan.
 *
 * Every supplied asset is listed with its classification, so an empty
 * `restricted_jurisdictions` list is distinguishable from a missing one:
 * `coverage: "complete"` means every asset was classified (or its chain is out
 * of scope), and `execution_hold: true` means at least one asset is
 * unclassified and must not be executed.
 */
export interface JurisdictionAsset {
  chain_id: string;
  token: string;
  side: AssetSide;
  classification: AssetClassification;
  class_sources: string[];
  restricted_jurisdictions: string[];
  execution_hold: boolean;
}

export function quoteJurisdiction(assets: readonly RestrictableAsset[]) {
  const entries = assets.flatMap((asset): JurisdictionAsset[] => {
    if (asset.token === undefined) return [];
    const { classification, sources } = classifyAsset(asset.chainId, asset.token);
    return [{
      chain_id: BigInt(asset.chainId).toString(),
      token: hexAddress(asset.token),
      side: asset.side,
      classification,
      class_sources: [...sources],
      restricted_jurisdictions: [...restrictedJurisdictionsFor(classification)],
      execution_hold: classification === "unclassified",
    }];
  });
  return summarize(entries);
}

function summarize(entries: readonly JurisdictionAsset[]) {
  const restricted = [
    ...new Set(entries.flatMap((asset) => asset.restricted_jurisdictions)),
  ].sort();
  const hold = entries.some((asset) => asset.execution_hold);
  return {
    policy_version: JURISDICTION_POLICY_VERSION,
    coverage: hold ? ("incomplete" as const) : ("complete" as const),
    execution_hold: hold,
    restricted_jurisdictions: restricted,
    assets: entries,
    execution_notice: restricted.length > 0 || hold ? QUOTE_JURISDICTION_NOTICE : null,
  };
}

export type QuoteJurisdiction = ReturnType<typeof quoteJurisdiction>;

/**
 * One jurisdiction summary for a response that carries several swap plans, so
 * a caller deciding whether the whole batch can proceed reads one list instead
 * of walking every child. A hold on any child holds the batch.
 */
export function mergeQuoteJurisdictions(
  jurisdictions: readonly QuoteJurisdiction[],
): QuoteJurisdiction {
  return summarize(jurisdictions.flatMap((entry) => entry.assets));
}

/**
 * Record that the connection-country check ran and let the request through.
 * It describes the MCP connection only; it says nothing about the user's
 * domicile or eligibility and is not permission to trade.
 */
export function producerCountryGate(country: RequestCountry) {
  return {
    applied: true as const,
    policy_version: JURISDICTION_POLICY_VERSION,
    country_resolved: country !== null,
  };
}
